language: java
jdk:
- oraclejdk8
script: ant build
addons:
  sonarcloud:
    organization: "skariyadan-github" # the key of the org you chose at step #3
    token:
      secure: bf1ecfdce51ef92bf6ef5993e408231577f75ca9 # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
